name: Release tagged image

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract samba version
        id: samba
        run: |
          echo "version=$(sed -nr 's/^ARG SAMBA_VERSION=(.*)$/\1/p' Dockerfile)" >> "$GITHUB_OUTPUT"
      - name: Extract alpine version
        id: alpine
        run: |
          echo "version=$(grep -oE 'alpine:([^ ]+)' Dockerfile | head -1 | cut -d: -f2)" >> "$GITHUB_OUTPUT"
      - name: Generate tag
        id: tag
        run: |
          echo "bare=v${{ steps.samba.outputs.version }}" >> "$GITHUB_OUTPUT"
          echo "distro=v${{ steps.samba.outputs.version }}-alpine${{ steps.alpine.outputs.version }}" >> "$GITHUB_OUTPUT"
          echo "full=v${{ steps.samba.outputs.version }}-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/samba-docker:${{ steps.tag.outputs.bare }}
            ghcr.io/${{ github.repository_owner }}/samba-docker:${{ steps.tag.outputs.distro }}
            ghcr.io/${{ github.repository_owner }}/samba-docker:${{ steps.tag.outputs.full }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
